add sql file for L1 lgd_orders
Logee-Data/logee-dwh pull request #12
Opened 2022-06-17 04:13 UTC by fikrihaykal41

first version L1 lgd_orders

2022-06-17 08:56 UTC, toileto requested changes
Check comment ya @fikrihaykal41 🙇‍♂️

2022-06-17 08:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_orders.sql
> +  JSON_EXTRACT_SCALAR(A.data, '$.urlSalesOrderPdf') AS url_sales_order_pdf,
Mungkin bisa di `NULL` - in aja kalau dia kosong

2022-06-17 08:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_orders.sql
> +      IF(JSON_EXTRACT_SCALAR(list_address, '$.addressMark') = "", NULL, JSON_EXTRACT_SCALAR(list_address, '$.addressMark')) AS address_mark
Ini kayanya harus gini deh

```sql

IF(
    JSON_EXTRACT_SCALAR(list_address, '$.addressMark') IN ("", "\"\""), 
    NULL,
    JSON_EXTRACT_SCALAR(list_address, '$.addressMark')
)

```

2022-06-17 08:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_orders.sql
> +      IF(JSON_EXTRACT_SCALAR(data, '$.store.mainAddress.addressMark') = "", NULL, JSON_EXTRACT(data, '$.store.mainAddress.addressMark')) AS address_mark
Ini juga sama

```sql
IF(JSON_EXTRACT_SCALAR(data, '$.store.mainAddress.addressMark') IN ("", "\"\""), NULL, JSON_EXTRACT(data, '$.store.mainAddress.addressMark'))
```

2022-06-20 04:58 UTC, fikrihaykal41 reviewed
sudah ku revisi mas

2022-06-20 07:28 UTC, ameliaksalwa approved these changes
superr sekalii menurut hasil review aku sudah sesuai semua, approve

2022-06-21 14:02 UTC, toileto requested changes
Good job mas @fikrihaykal41! 

![](https://i.giphy.com/media/8SyzTfbhThVNS/giphy.gif)

Love how the code is structured, it's clean!

Anyway, sebelum di release, there are several improvements ya sedikit soal query ini.

2022-06-22 02:06 UTC, fikrihaykal41 reviewed
sudah ku revisi ya mas

2022-06-22 02:35 UTC, toileto approved these changes
Cakep

![](https://i.giphy.com/media/5BTyQlNh8Ugmc/giphy.gif)

2022-06-22 02:43 UTC, merged