Create lgd_voucher.sql
Logee-Data/logee-dwh pull request #13
Opened 2022-06-17 08:07 UTC by meliskapurnama

2022-06-17 08:58 UTC, toileto requested changes
Check comment yaaa @meliskapurnama 🙇

2022-06-17 08:58 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_voucher.sql
> +  REPLACE(JSON_EXTRACT(A.data, '$.companyGroupIds'), '"', '') AS company_group_ids,
Ini belum dalam bentuk `ARRAY` nih @meliskapurnama

2022-06-18 17:28 UTC, toileto requested changes
Overall sudah oke, tinggal ada improvement sedikit yaaaa 🙇

2022-06-18 17:28 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_voucher.sql
> +    UNNEST(JSON_EXTRACT_ARRAY(data, '$.company_group_ids ')) AS company_group_ids
1. Ini extractnya dari `'$.companyGroupIds'`

NP: Extractor nya dia ga perlu ada spasi yaaa

2022-06-18 17:28 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_voucher.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.amount'), '"', '') AS INT64) AS amount,
Untuk masalah duit duit, selalu pakai `FLOAT64` yaaa

2022-06-19 16:33 UTC, toileto approved these changes
Approved

![](https://i.giphy.com/media/fYlennPcKut8gjKOZD/giphy.gif)

2022-06-20 04:15 UTC, fikrihaykal41 approved these changes
Approved!

2022-06-20 11:27 UTC, merged