Create dma_logee_companies.sql
Logee-Data/logee-dwh pull request #15
Opened 2022-06-17 08:32 UTC by meliskapurnama

table dma_logee_companies

2022-06-17 09:06 UTC, toileto requested changes
Masih contain error nih @meliskapurnama 

Di check lagi yaaaa 🙇 

<img width="528" alt="Screen Shot 2022-06-17 at 16 06 38" src="https://user-images.githubusercontent.com/33114786/174266411-a45d06a9-4b22-4e4a-b28e-d6a3878f72fc.png">

2022-06-17 14:51 UTC, meliskapurnama commented
> Masih contain error nih @meliskapurnama
> 
> Di check lagi yaaaa 🙇
> 
> <img alt="Screen Shot 2022-06-17 at 16 06 38" width="528" src="https://user-images.githubusercontent.com/33114786/174266411-a45d06a9-4b22-4e4a-b28e-d6a3878f72fc.png">

2022-06-17 14:54 UTC, meliskapurnama commented
malam kak, maaf sebelumnya aku ada coba test run lagi di prod lalu datanya keluar kak atau aku coba ulang push lagi kah kak?

2022-06-18 17:08 UTC, toileto requested changes
@meliskapurnama ada sedikit input dari aku ya, see comments

2022-06-18 17:08 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_companies.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.bankTransferCode'), '"', '') AS INT64) AS bank_transfer_code,
Untuk tipe data nya, karena angka disini sebagai identifier (ID, dimension), bukan sesuatu yang perlu diukur (metrics), jadi nya tipe nya sebaiknya STRING yaaa

2022-06-18 17:08 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_companies.sql
> +  REPLACE(JSON_EXTRACT(A.data, '$.feePercentage'), '"', '') AS fee_percentage,
Ini dia isi nya fungsi nya sebagai mathematical value, jadi sebaiknya pakai `FLOAT64` yaaa

2022-06-18 17:08 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_companies.sql
> +      REPLACE(allowed_payment_type, '"', '')
Jadikan `DISTINCT REPLACE(allowed_payment_type, '"', '')` ya

Aku check soalnya dia isinya bisa duplikat

2022-06-18 17:08 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_companies.sql
> +      REPLACE(partner_ids, '"', '')
Jadikan `DISTINCT REPLACE(partner_ids, '"', '')` ya

Aku check soalnya dia isinya bisa duplikat

2022-06-19 16:41 UTC, toileto approved these changes
Overall sudah oke.

@fikrihaykal41 for future reference, nanti revisit table ini untuk nambahin handler string kosong yaaa

2022-06-20 10:38 UTC, fikrihaykal41 approved these changes
sejauh aku lihat sudah oke, aku sih yes

2022-06-20 15:00 UTC, merged