lgd_users
Logee-Data/logee-dwh pull request #19
Opened 2022-06-17 14:37 UTC by kellylanjaya

2022-06-17 15:02 UTC, toileto requested changes
@kellylanjaya, overall sudah oke, cuma ada beberapa point improvement

1. Yang `.DS_Store` nya di hapusin dulu yaaa 😁 
2. Jangan lupa kalau udah mau release, table nya ganti di FROM nya buat ke `prod`
3. Ketimbang camelCase, pakainya snake_case yaaaa

See comments untuk point 2 & 3 for further details yaaaa 🙇

2022-06-20 08:19 UTC, ameliaksalwa requested changes
crosscheck yaa

2022-06-21 08:46 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah oke, aku sih yes

2022-06-21 11:40 UTC, toileto requested changes
Ada sedikit comment yaaaaa

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +      IF(REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.lat'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.lat'), '"', ''))  AS lat,
```IF(REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.lat'), '"', '') = "", NULL, CAST(REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.lat'), '"', '') AS FLOAT64)```

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +      IF(REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.long'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.long'), '"', ''))  AS long,
```IF(REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.long'), '"', '') = "", NULL, CAST(REPLACE(JSON_EXTRACT_SCALAR(list_address, '$.long'), '"', '') AS FLOAT64) AS long,```

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +      CAST(JSON_EXTRACT_SCALAR(data, '$.usermetadata.mainAddress.phoneNumber') AS INT64) AS phone_number,
`STRING` yaaaa phone_number

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +      CAST(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerPhoneNumber'), '"', '') AS INT64) AS owner_phone_number,
Ini jug jadikan ke `STRING` yaaa

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +        IF(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.lat'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.lat'), '"',
```IF(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.lat'), '"', '') = "", NULL, CAST(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.lat'), '"', '') AS FLOAT64)) AS lat```

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +        IF(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.long'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.long'), '"'
```IF(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.long'), '"', '') = "", NULL, CAST(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.storeOwner.ownerAddress.long'), '"', '') AS FLOAT64)```

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +      CAST(REPLACE(JSON_EXTRACT_SCALAR(data, '$.usermetadata.integratedAccount.tmoney.phoneNo'), '"', '') AS INT64) AS phone_number,
Ke `STRING` yaaa

2022-06-21 11:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_users.sql
> +      IF(REPLACE(JSON_EXTRACT(A.data, '$.usermetadata.approvedAt'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT(A.data, '$.usermetadata.approvedAt'), '"', '')) AS approved_at,
Kalau dari namanya, ini hasilnya harus di cast ke TIMESTAMP kayanya

Jadi:

```IF(REPLACE(JSON_EXTRACT(A.data, '$.usermetadata.approvedAt'), '"', '') = "", NULL, CAST(REPLACE(JSON_EXTRACT(A.data, '$.usermetadata.approvedAt'), '"', '') AS TIMESTAMP))```

2022-06-22 05:54 UTC, toileto approved these changes
Approved

![](https://i.giphy.com/media/vYRlHW3gw4VuU/giphy.gif)

2022-06-22 05:55 UTC, merged