dma_logee_vehicles
Logee-Data/logee-dwh pull request #20
Opened 2022-06-17 14:41 UTC by kellylanjaya

2022-06-17 14:51 UTC, toileto requested changes
Overall sudah oke. Cuma ada sedikit yang perlu di improve.

See comment yaaa @kellylanjaya

2022-06-17 14:51 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +FROM `logee-data-dev.logee_datalake_raw_development.visibility_dma_logee_vehicles`
Di ganti yaaa, dari `logee-data-dev.logee_datalake_raw_development.visibility_dma_logee_vehicles` ke `logee-data-prod.logee_datalake_raw_production.visibility_dma_logee_vehicles`

2022-06-17 14:51 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +  CAST(JSON_EXTRACT_SCALAR(data, '$.capacityWeight') AS INT64) AS capacity_weight,
Ini casting nya diganti ke `FLOAT64` dari `INT64`

2022-06-18 17:31 UTC, toileto requested changes
~~Double Post~~

2022-06-18 17:40 UTC, toileto requested changes
Ada tambahan sedikit dari update terakhirnya. Check comment nya yaaa

Sama tambahan, ini ada file lain yang kebawa 😁

Kalau pakai GitHub desktop, bisa coba refer kesini yaaa: [Selecting changes to include in a commit](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project#selecting-changes-to-include-in-a-commit)

2022-06-18 17:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +FROM logee-data-prod.logee_datalake_raw_production.visibility_dma_logee_vehicles
Jangan lupa backtick `` ` `` di depan dan belakang nama table nya yaaa

2022-06-18 17:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +LIMIT 1000
`LIMIT` statement nya juga di remove yaaa

2022-06-18 17:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +  CAST(REPLACE(JSON_EXTRACT(data, '$.kirExpiryDate'), '"', '') AS TIMESTAMP) AS kir_expiry_date,
Barusan aku check, dia data HOUR nya ga ada, jadi di cast ke `DATE` aja yaaa ketimbang `TIMESTAMP`

2022-06-18 17:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +  CAST(REPLACE(JSON_EXTRACT(data, '$.stnkExpiryDate'), '"', '') AS TIMESTAMP) AS stnk_expiry_date,
Ini juga sama ni, jadikan `DATE` yaaa

2022-06-18 17:40 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +  CAST(JSON_EXTRACT_SCALAR(data, '$.wheels') AS FLOAT64) AS wheels,
Untuk `wheels` jadikan `INT64` yaa

2022-06-20 04:12 UTC, ameliaksalwa requested changes
untuk view yang di dev di save menyesuaikan resourcenya yaitu `logee-data-dev.logee_datalake_raw_development.visibility_dma_logee_vehicles`. dilanjutkan copy paste query ke prod dengan resource `logee-data-prod.logee_datalake_raw_production.visibility_dma_logee_vehicles` dan disesuaikan apakah datanya sama dengan dev/diperlukan improvement query.

untuk commit di github menggunakan resource prod

2022-06-20 04:12 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_vehicles.sql
> +  DATE(REPLACE(JSON_EXTRACT(data, '$.stnkExpiryDate'), '"', '')) stnk_expiry_date,
kurang 'AS' sebelum 'stnk_expiry_date' untuk penamaan field data

2022-06-20 04:38 UTC, fikrihaykal41 reviewed
eeee ini 2 table dalam 1 branch ya?

2022-06-20 06:35 UTC, ameliaksalwa approved these changes
approveee

2022-06-20 10:54 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah oke, aku sih yes

2022-06-28 03:16 UTC, merged