add sql file for L1 lgd_attendance
Logee-Data/logee-dwh pull request #22
Opened 2022-06-20 05:06 UTC by ameliaksalwa

first version L1 lgd_attendance

2022-06-20 05:11 UTC, fikrihaykal41 requested changes
punteun

2022-06-20 05:11 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +  JSON_EXTRACT(data, '$.isDeleted') AS is_deleted,
Sepertinya `is_deleted` seharusnya di-`CAST` jadi `BOOLEAN`

2022-06-20 05:22 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +  JSON_EXTRACT(data, '$.isDeleted') AS is_deleted,
Ayay sudah diperbaiki Mas Haykal

2022-06-20 05:37 UTC, fikrihaykal41 reviewed
punteun again

2022-06-20 05:37 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +      ) AS location
maap banget kelewat, kayanya isi dari array `location` ini bisa lebih clean lagi deh pake `JSON_EXTRACT_SCALAR`
![image](https://user-images.githubusercontent.com/22905062/174532058-ba3b5ef3-7a27-4f3b-b80a-4e18b16824ca.png)
masih ada petik dua (`"`) yg ketinggalan huehuehue

2022-06-20 05:37 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +  ) AS track_activities
ini juga

2022-06-20 05:38 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +  ) AS track_activities
eh kurang atas ternyata maap

2022-06-20 05:57 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +  ) AS track_activities
done yaa

2022-06-20 06:17 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah clear, dari aku yes

2022-06-20 15:11 UTC, toileto requested changes
Very good so far. But there are some improvements yaaa 😁

2022-06-20 15:11 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_track_activities, '$.location.lat') AS location_lat,
Ini karena `location` nya sudah ada di atas nya, jadi cukup dinamain sebagai `lat` aja yaaa

2022-06-20 15:11 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_track_activities, '$.location.long') AS location_long
Ini juga ya `long` aja ya

2022-06-20 15:11 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +      CAST(JSON_EXTRACT_SCALAR(pre_attendances, '$.date') AS TIMESTAMP) AS attendances_date,
Ini kaya nya jadikan aja `DATE(JSON_EXTRACT_SCALAR(pre_attendances, '$.date'))` yaaa

2022-06-20 15:11 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_attendances, '$.location.lat') AS attendances_location_lat,
Yang 2 dibawah (36-37) ini juga di ke `lat` dan `long` ya

2022-06-20 15:11 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +  CAST(JSON_EXTRACT_SCALAR(data, '$.date') AS TIMESTAMP) AS date,
Jadikan `DATE(JSON_EXTRACT_SCALAR(data, '$.date') AS date` yaaa

2022-06-21 02:31 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_track_activities, '$.location.lat') AS location_lat,
ayay, done Mas

2022-06-21 02:31 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_track_activities, '$.location.long') AS location_long
ayay, done Mas

2022-06-21 02:31 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +      CAST(JSON_EXTRACT_SCALAR(pre_attendances, '$.date') AS TIMESTAMP) AS attendances_date,
ayay, done Mas

2022-06-21 02:31 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_attendances, '$.location.lat') AS attendances_location_lat,
ayay, done Mas

2022-06-21 13:50 UTC, toileto requested changes
Ada sedikit improvement yaaaa

2022-06-21 13:50 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_track_activities, '$.location.lat') AS lat,
Ini dia di cast ke FLOAT ya mba Amel, ada baik nya dibikin seperti ini:

```
IF(REPLACE(JSON_EXTRACT(pre_track_activities, '$.location.lat'), '"', '') = '', NULL, CAST(REPLACE(JSON_EXTRACT(pre_track_activities, '$.location.lat'), '"', '') AS FLOAT64)) AS lat
```

2022-06-21 13:50 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_track_activities, '$.location.long') AS long
Ini sama dengan `lat` yaaa

2022-06-21 13:50 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_attendance.sql
> +        JSON_EXTRACT(pre_attendances, '$.location.long') AS long
Ini juga

2022-06-22 02:41 UTC, toileto approved these changes
Approved

![](https://i.giphy.com/media/jt8owSL9Tat34fbp67/giphy.gif)

2022-06-22 06:00 UTC, merged