Create dma_logee_user.sql
Logee-Data/logee-dwh pull request #23
Opened 2022-06-20 06:30 UTC by meliskapurnama

table dma_logee_user

2022-06-20 08:04 UTC, ameliaksalwa requested changes
cek comment yaaw

2022-06-21 02:06 UTC, fikrihaykal41 requested changes
punteun

2022-06-21 02:06 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_user.sql
> +  WHERE _date_partition = "2022-06-20" LIMIT 1000
`date_partition`-nya diubah jadi `2022-01-01` yaa, sama `LIMIT 1000`-nya diilangin aja

2022-06-21 04:44 UTC, ameliaksalwa requested changes

2022-06-21 04:44 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/dma_logee_user.sql
> +  WHERE _date_partition = "2022-01-01"
punten sedikit nambahin untuk where clause nya `WHERE _date_partition >= "2022-01-01"`

2022-06-21 06:12 UTC, ameliaksalwa approved these changes
Dari aku approved yay

2022-06-21 08:48 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah oke, aku sih yes

2022-06-22 02:42 UTC, toileto approved these changes
Approved

![](https://i.giphy.com/media/W5IsILVJix8U8GAI2R/giphy.gif)

2022-06-22 06:01 UTC, merged