add sql file for L1 lgd_sub_product
Logee-Data/logee-dwh pull request #24
Opened 2022-06-20 10:09 UTC by fikrihaykal41

done by Velly Ibrahim, but tackled by Fikri Haykal

2022-06-20 13:25 UTC, ameliaksalwa requested changes
punten ada beberapa poin hasil review, cmiiw yess

2022-06-20 13:25 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.subProductWeight'), '"', '') AS INT64) AS sub_product_weight,
punten crosscheck untuk data type 
'price'     : int -> float
'weight'  : int -> float

2022-06-20 13:25 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.isTax'), '"', '') AS BOOL) AS is_tax,
crosscheck kurang 1 field 'subProductStockOnHold'
![image](https://user-images.githubusercontent.com/106147357/174611579-b59b3e4e-fa93-4b8e-bb0e-b78476b5fc2c.png)

2022-06-21 05:32 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.subProductWeight'), '"', '') AS INT64) AS sub_product_weight,
sudah ku revisi ya mbaa

2022-06-21 05:32 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql
> +        IF(JSON_EXTRACT_SCALAR(booked_stock, '$.stock') = "", NULL, JSON_EXTRACT_SCALAR(booked_stock, '$.stock')) AS stock
sudah ku revisi ya mbaa

2022-06-21 05:33 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.isTax'), '"', '') AS BOOL) AS is_tax,
sudah ku revisi ya mbaa

2022-06-21 06:06 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_sub_product.sql
> +  CAST(REPLACE(JSON_EXTRACT(A.data, '$.isTax'), '"', '') AS BOOL) AS is_tax,
mantaaap

2022-06-21 06:09 UTC, ameliaksalwa approved these changes
Review dari aku sepertinya udah semua, approved

2022-06-22 02:52 UTC, toileto approved these changes
Approved

![](https://media.giphy.com/media/lDT56lCmFnTt6/giphy.gif)

2022-06-22 06:01 UTC, merged