create lgd_store
Logee-Data/logee-dwh pull request #25
Opened 2022-06-20 13:49 UTC by aliaismayanti

2022-06-21 03:40 UTC, ameliaksalwa requested changes
punten ada beberapa poin review, cmiiw sist

2022-06-21 03:40 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +  REPLACE(JSON_EXTRACT(A.data, '$.modifiedBy'), '"', '') AS modified_by,
punten sepertinya ada field yang belum masuk berdasarkan original_data : status, assignedTaskId, createdBy, isDeleted, isActive
![image](https://user-images.githubusercontent.com/106147357/174711071-94c41104-7ba0-4a4b-ba6d-45ee6538e40d.png)

2022-06-21 03:40 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +       IF(REPLACE(JSON_EXTRACT(data, '$.storeOwner.ownerAddress.cityId'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT(data, '$.storeOwner.ownerAddress.cityId'), '"', '')) AS city_d,
typo penulisan alias 'city_d' --> 'city_id'

2022-06-21 03:40 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +  ) AS mainAddress,
ketentuan penulisan ke snake_case, cmiiw

2022-06-21 08:47 UTC, aliaismayanti commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +  ) AS mainAddress,
ohh iya, siapp

2022-06-22 02:56 UTC, toileto requested changes
Ada sedikit improvement yaaa @aliaismayanti, overall sudah oke kok 😁

2022-06-22 02:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +   CAST(REPLACE(JSON_EXTRACT_SCALAR(A.data, '$.isDeleted'), '"', '') AS BOOL) AS isDeleted,
Ke snake_case yaaa @aliaismayanti

2022-06-22 02:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +    CAST(REPLACE(JSON_EXTRACT_SCALAR(A.data, '$.isActive'), '"', '') AS BOOL) AS isActive,
Ini juga ada sedikit ke snake_case yaaa

2022-06-22 02:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +    REPLACE(JSON_EXTRACT_SCALAR(A.data, '$.mainAddress.lat'), '"', '') AS lat,
Ini cast jadikan `FLOAT64` yaaa

2022-06-22 02:56 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_store.sql
> +    REPLACE(JSON_EXTRACT_SCALAR(A.data, '$.mainAddress.long'), '"', '') AS long,
Ini cast jadikan `FLOAT64` yaaa

2022-06-22 04:22 UTC, fikrihaykal41 reviewed
jangan lupa direvisi ya @aliaismayanti

2022-06-28 03:17 UTC, fikrihaykal41 approved these changes
sejauh yg kulihat sudah aman, aku sih yes

2022-07-01 05:15 UTC, ameliaksalwa approved these changes
mantappu, approved yey

2022-07-01 09:10 UTC, closed without merging