commit lgd_product
Logee-Data/logee-dwh pull request #30
Opened 2022-06-24 05:31 UTC by AmeliaKurniaSalwa

punteun koreksi dan sarannya Mas Mas

2022-07-05 07:13 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 07:13 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_product.sql
> +  WHERE product_length IS NULL or product_length <= 0
ada error ini
![image](https://user-images.githubusercontent.com/22905062/177270866-9629e421-c55a-4636-bd59-2e924b25cb44.png)

2022-07-12 07:21 UTC, fikrihaykal41 approved these changes
sogudd, approved

2022-07-12 07:46 UTC, aliaismayanti approved these changes
nice, aproved!

2022-07-13 03:30 UTC, merged