Create lgd_voucher.sql
Logee-Data/logee-dwh pull request #34
Opened 2022-06-24 08:29 UTC by meliskapurnama

permisi kakak-kakak, mohon saran ataupun koreksinya..
Terima kasih^^

2022-06-27 00:41 UTC, ameliaksalwa requested changes

2022-06-27 00:41 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/lgd_voucher.sql
> +  WHERE is_deleted IS NULL
punteun exclude query untuk field `is_deleted` karena termasuk metadata cmiiw

2022-07-05 06:35 UTC, ameliaksalwa approved these changes
dari aku sepertinya sudah aman, approved yey

2022-07-05 07:20 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah oke, approved

2022-07-05 07:51 UTC, merged