add L2 lgd_brand
Logee-Data/logee-dwh pull request #36
Opened 2022-06-24 09:07 UTC by fikrihaykal41

2022-06-27 01:12 UTC, ameliaksalwa requested changes

2022-06-27 01:12 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/lgd_brand.sql
> +    is_deleted IS NULL
punteun Mas, exclude query untuk field `is_deleted` karena termasuk metadata cmiiw

2022-06-29 01:52 UTC, fikrihaykal41 commented on source/sql/dwh/bq_view/L2/visibility/lgd_brand.sql
> +    is_deleted IS NULL
sudah ku revisi mba, monggo dicek lagi

2022-07-05 06:47 UTC, ameliaksalwa approved these changes
approved yey

2022-07-12 08:01 UTC, aliaismayanti approved these changes
so far so good

2022-07-12 08:03 UTC, merged