add lgd_companies l2
Logee-Data/logee-dwh pull request #40
Opened 2022-06-28 08:55 UTC by aliaismayanti

2022-06-29 01:39 UTC, ameliaksalwa requested changes

2022-06-29 01:39 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/lgd_companies.sql
> +      'provinuser_idce_name' AS column,
punteun typo penulisan nama kolom sist

2022-06-29 01:39 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/lgd_companies.sql
> +  WHERE is_deleted IS NULL
punteun exclude query untuk field `is_deleted` karena termasuk metadata cmiiw

2022-06-29 01:39 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/lgd_companies.sql
> +
punteun kurang quality check untuk field `companyGroup_id' sist

2022-06-29 03:16 UTC, aliaismayanti commented on source/sql/dwh/bq_view/L2/visibility/lgd_companies.sql
> +
done update all @ameliaksalwa

2022-07-04 04:54 UTC, ameliaksalwa requested changes

2022-07-04 04:54 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/lgd_companies.sql
> +  FROM `logee-data-prod.L1_visibility.lgd_companies`
punteun kurang filtering `where` berdasarkan `execution_date`, referensi lengkapnya ada di lgd_orders

2022-07-05 07:27 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah oke, approved

2022-07-06 06:25 UTC, ameliaksalwa approved these changes
approved

2022-07-07 09:21 UTC, merged