add lgd store l2
Logee-Data/logee-dwh pull request #41
Opened 2022-06-28 09:03 UTC by aliaismayanti

2022-06-29 01:56 UTC, ameliaksalwa requested changes

2022-06-29 01:56 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/lgd_store.sql
> +  WHERE is_deleted IS NULL
punteun exclude query untuk field is_deleted karena termasuk metadata cmiiw

2022-07-05 07:32 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 07:32 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_store.sql
> +  WHERE is_active IS NULL
ini juga sepertinya bisa diilangin karena termasuk metadata

2022-07-06 06:20 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah oke, approved

2022-07-06 06:28 UTC, ameliaksalwa approved these changes
dari aku seperetinya udah sesuai, approved yey

2022-07-07 09:22 UTC, merged