Create L2 dma_logee_delivery_details
Logee-Data/logee-dwh pull request #43
Opened 2022-06-29 01:27 UTC by RendiKustiawan

2022-06-29 04:52 UTC, ameliaksalwa requested changes

2022-06-29 04:52 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/dma_logee_delivery_details.sql
> +
punteun kurang `quality check` untuk field
a. available_to_all
b. pick_up_time
c. is_paid
d. send_company_partner_firt
e. destination_count
f. fulfillment

2022-06-29 04:52 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L2/visibility/dma_logee_delivery_details.sql
> +
punteun terdapat beberapa field yang perlu `TO_HEX` karena termasuk Personal Identification Information (PII), antara lain:
a. origin_pic_phone
b. destination_pic_phone
c. fulfillment.driver_phone
d. fulfillment.driver_sim_number
e. fulfillment.vehicle_police_num
cmiiw

2022-07-05 08:08 UTC, toileto commented
I think we need to retake this over @fikrihaykal41

2022-07-05 08:08 UTC, closed without merging