add sql file for lgd_category
Logee-Data/logee-dwh pull request #6
Opened 2022-06-15 01:32 UTC by fikrihaykal41

first commit for `lgd_category`

2022-06-15 03:14 UTC, toileto requested changes
Check comment yaaa Haykal

2022-06-15 03:14 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_category.sql
> +FROM `logee-data-dev.logee_datalake_raw_development.visibility_lgd_category`
Jangan lupa di ganti ke `logee-data-prod.logee_datalake_raw_production` yaaa

2022-06-15 03:14 UTC, toileto commented on source/sql/dwh/bq_view/L1/visibility/lgd_category.sql
> +  CAST(REPLACE(JSON_EXTRACT(data, '$.totalProductBind'), '"', '') AS INT64) AS total_productbind,
Mungkin dibikin `total_product_bind` aja

2022-06-15 03:26 UTC, fikrihaykal41 reviewed
oke oke

2022-06-16 04:40 UTC, ameliaksalwa approved these changes

2022-06-16 07:15 UTC, merged