Create L2 dma_logee_companies
Logee-Data/logee-dwh pull request #61
Opened 2022-06-29 15:31 UTC by meliskapurnama

2022-07-05 07:38 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 07:38 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE latitude IS NULL or latitude <= 0
kayanya kalau `latitude` nilainya bisa negatif deh, jadi kayanya ini cukup `WHERE latitude IS NULL or latitude = 0`

2022-07-05 07:38 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE longitude IS NULL or longitude <= 0
kayanya kalau `longitude` nilainya bisa negatif deh, jadi kayanya ini cukup `WHERE longitude IS NULL or latitude = 0`

2022-07-05 07:38 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE siup_expiry_date IS NULL
sepertinya ini kurang kondisi untuk `empty string`-nya

2022-07-05 07:38 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE pks_expiry_date IS NULL
sepertinya ini kurang kondisi untuk `empty string`-nya

2022-07-05 07:38 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE is_active IS NULL
ini sepertinya bisa diilangin karena termasuk metadata

2022-07-07 05:28 UTC, ameliaksalwa requested changes

2022-07-07 05:28 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE pks_expiry_date IS NULL
query ter-update belum diedit untuk kondisi `empty string` + `or pks_expiry_date = ''`
![image](https://user-images.githubusercontent.com/106147357/177697586-fe8c93cc-18c8-4b6b-a08e-9ec04ff97093.png)

2022-07-07 05:28 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE siup_expiry_date IS NULL
query ter-update belum diedit untuk kondisi `empty string` + or `siup_expiry_date= ''`
![image](https://user-images.githubusercontent.com/106147357/177697722-e64766a7-27f2-4764-9ae4-a5f7b29a9c94.png)

2022-07-07 05:28 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/dma_logee_companies.sql
> +  WHERE longitude IS NULL or longitude <= 0
karena `longitude` value bisa bernilai negatif atau sama dengan 0, jadi untuk filtering condition cukup `WHERE longitude  IS NULL`

2022-07-07 05:28 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE longitude IS NULL or longitude = 0
karena `longitude` value bisa sama dengan 0, jadi untuk filtering condition cukup `WHERE longitude IS NULL`

2022-07-07 05:28 UTC, ameliaksalwa commented on source/sql/dwh/bq_view/L1/dma_logee_companies.sql
> +  WHERE latitude IS NULL or latitude <= 0
karena `latitude` value bisa bernilai negatif atau sama dengan 0, jadi untuk filtering condition cukup `WHERE latitude IS NULL`

2022-07-07 05:28 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE latitude IS NULL or latitude  = 0
karena `latitude`value bisa sama dengan 0, jadi untuk filtering condition cukup `WHERE latitude IS NULL`

2022-07-07 08:14 UTC, meliskapurnama commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE longitude IS NULL or longitude = 0
soree kak amel, maaf kak setau ku karena siup_expiry_date dan pks_expiry_date itu dalam bentuk date ga bisa pake or siup_expiry_date= '' dan pks_expiry_date = '' kalau aku tidak salah juga jadinya kondisinya dibikin null aja kak

2022-07-08 02:53 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_companies.sql
> +  WHERE longitude IS NULL or longitude = 0
oooh i see, thank you infonya meliska

2022-07-08 02:56 UTC, ameliaksalwa approved these changes
sejauh yang aku lihat sudah aman, approved

2022-07-12 01:52 UTC, fikrihaykal41 approved these changes
approved

2022-07-12 01:53 UTC, merged