L2 lgd_users
Logee-Data/logee-dwh pull request #64
Opened 2022-06-29 17:08 UTC by kellylanjaya

2022-06-29 19:35 UTC, toileto commented
Kita tunggu (https://github.com/Logee-Data/logee-dwh/pull/62) release dulu yaaa sebelum release ini

2022-07-05 07:49 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 07:49 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_users.sql
> +  WHERE login_count IS NULL
sepertinya ini kurang kondisi untuk `empty string`-nya dan karena ini tipe datanya `integer` kayanya belum ada untuk error handling integer

2022-07-05 07:49 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_users.sql
> +  WHERE user_metadata.store_owner.owner_address.lat IS NULL or user_metadata.store_owner.owner_address.lat <= 0
sepertinya untuk `latitude` value-nya bisa negatif, jadi kayanya bagian ini cukup `WHERE user_metadata.store_owner.owner_address.lat IS NULL or user_metadata.store_owner.owner_address.lat = 0` dan `"Column can not be a negative number"` bisa diilangin

2022-07-05 07:49 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_users.sql
> +  WHERE user_metadata.store_owner.owner_address.long IS NULL or user_metadata.store_owner.owner_address.long <= 0
sepertinya untuk `longitude` value-nya bisa negatif, jadi kayanya bagian ini cukup `WHERE user_metadata.store_owner.owner_address.long IS NULL or user_metadata.store_owner.owner_address.long = 0`

2022-07-05 07:49 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_users.sql
> +  WHERE user_metadata.main_address.long IS NULL or user_metadata.main_address.long <= 0
sepertinya untuk `longitude` value-nya bisa negatif, jadi kayanya bagian ini cukup `WHERE user_metadata.store_owner.owner_address.long IS NULL or user_metadata.store_owner.owner_address.long = 0`

2022-07-07 05:14 UTC, ameliaksalwa requested changes

2022-07-07 05:14 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/lgd_users.sql
> +  WHERE user_metadata.main_address.lat IS NULL or user_metadata.main_address.lat = 0
karena `latitude` value bisa sama dengan 0, jadi untuk filtering condition cukup ` WHERE user_metadata.main_address.lat IS NULL` seperti query pada line 543-548

2022-07-07 05:14 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/lgd_users.sql
> +  WHERE user_metadata.main_address.long IS NULL or user_metadata.main_address.long <= 0
karena `longitude` value bisa bernilai negatif atau sama dengan 0, jadi untuk filtering condition cukup `WHERE user_metadata.main_address.long IS NULL` seperti query pada line 556-561

2022-07-09 06:20 UTC, merged