update lgd_companies to airflow
Logee-Data/logee-dwh pull request #68
Opened 2022-06-30 04:46 UTC by aliaismayanti

2022-06-30 05:57 UTC, ameliaksalwa requested changes

2022-06-30 05:57 UTC, ameliaksalwa commented on dags/source/sql/dwh/L1/visibility/lgd_companies.sql
>    A.data AS original_data,
punteun belum di remove kolom `original_data`

2022-07-01 03:21 UTC, fikrihaykal41 requested changes
punteun

2022-07-01 03:21 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L1/visibility/lgd_companies.sql
> +  IF(REPLACE(JSON_EXTRACT(A.data, '$.companyGroupId'), '"', '') = "", NULL, REPLACE(JSON_EXTRACT(A.data, '$.companyGroupId'), '"', '')) AS companyGroup_id,
punteun, kayanya ini udah bener sebelumnya deh, jadi snake_case, dari `companyGroup_id` jadi `company_group_id`

2022-07-01 06:30 UTC, toileto approved these changes
Approved

![](https://i.giphy.com/media/WQr2txk5iEYUS6Kv3d/giphy.gif)

2022-07-01 06:30 UTC, ameliaksalwa approved these changes
Approved yey

2022-07-01 06:48 UTC, fikrihaykal41 approved these changes
approved

2022-07-01 06:48 UTC, merged