Create L2 dma_logee_user
Logee-Data/logee-dwh pull request #69
Opened 2022-06-30 06:13 UTC by meliskapurnama

2022-07-05 07:52 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 07:52 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_user.sql
> +  WHERE user_meta.is_registering_from_app IS NULL
sepertinya ini kurang kondisi untuk `empty string`-nya

2022-07-05 07:52 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/dma_logee_user.sql
> +  WHERE is_active IS NULL
sepertinya ini bisa diilangin karena termasuk metadata

2022-07-06 07:31 UTC, ameliaksalwa requested changes

2022-07-06 07:31 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_user.sql
> +  WHERE name IS NULL or name = ''
punteun kolom `name` belum ke masking

2022-07-06 07:31 UTC, ameliaksalwa commented on dags/source/sql/dwh/L2/visibility/dma_logee_user.sql
> +
punteun belum ada quality check untuk `assign_indicar` dan `show_tracking` terkait dengan `data null`

2022-07-12 01:47 UTC, fikrihaykal41 approved these changes
approved

2022-07-12 02:01 UTC, ameliaksalwa approved these changes
approved yey

2022-07-12 02:01 UTC, merged