dma_logee_driver to airflow
Logee-Data/logee-dwh pull request #70
Opened 2022-06-30 06:50 UTC by RendiKustiawan

2022-06-30 08:42 UTC, ameliaksalwa requested changes
punteun edit commitnya bukan di `bq_view`, tapi `dags -> source -> sql -> dwh -> L1 -> visibility`

2022-07-01 03:24 UTC, fikrihaykal41 requested changes
punteun

2022-07-01 03:24 UTC, fikrihaykal41 commented on dags/config/L1/visibility/dma_logee_driver.yaml
> +time_partitioning: published_timestamp
soalnya dipake disini kolom `published_timestamp`-nya

2022-07-01 03:24 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L1/visibility/dma_logee_drivers.sql
>    ts AS published_timestamp
kayanya `published_timestamp` tipe datanya masih `STRING` deh, belum `TIMESTAMP`

2022-07-01 04:34 UTC, toileto commented
Branch is taken over from Rendi. New PR is available here yaa: https://github.com/Logee-Data/logee-dwh/pull/75

2022-07-01 04:34 UTC, closed without merging