submit query lgd-attendance-airflow
Logee-Data/logee-dwh pull request #74
Opened 2022-06-30 08:13 UTC by Wina27

submit airflow

2022-06-30 08:49 UTC, ameliaksalwa approved these changes
punteun dari aku sepertinya sudah sesuai semua, approved Mba yipi

2022-07-01 03:27 UTC, fikrihaykal41 requested changes
punteun

2022-07-01 03:27 UTC, fikrihaykal41 commented on dags/config/L1/visibility/lgd_attendance
> +time_partitioning: modified_at
kayanya file config ini belum ada file extension-nya (`.yaml`) ya?

2022-07-01 06:32 UTC, fikrihaykal41 approved these changes
Approved

2022-07-01 06:47 UTC, merged