submit query l2-lgd-attendance
Logee-Data/logee-dwh pull request #77
Opened 2022-07-04 05:57 UTC by Wina27

submit query l2-lgd-attendance

2022-07-05 07:54 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 07:54 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_attendance.sql
> +    original_data,
sepertinya ini bisa diubah jadi `attendance_id`

2022-07-05 07:54 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_attendance.sql
> +    original_data,
sepertinya ini bisa diubah jadi `attendance_id`

2022-07-05 07:54 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_attendance.sql
> +    original_data,
sepertinya ini bisa diubah jadi `attendance_id`

2022-07-05 07:54 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_attendance.sql
> +    original_data,
sepertinya ini bisa diubah jadi `attendance_id`

2022-07-05 07:54 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_attendance.sql
> +  ON A.sales_id = B.sales_id
sepertinya ini bisa diubah jadi `attendance_id`

2022-07-06 07:39 UTC, ameliaksalwa requested changes

2022-07-06 09:49 UTC, ameliaksalwa approved these changes
approved yey

2022-07-07 03:25 UTC, fikrihaykal41 approved these changes
approved

2022-07-11 02:08 UTC, merged