add l2-lgd-sub-product
Logee-Data/logee-dwh pull request #78
Opened 2022-07-04 06:23 UTC by Wina27

submit query l2-lgd-sub-product

2022-07-05 08:04 UTC, fikrihaykal41 requested changes
punteun

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +check AS (
sepertinya ini kurang tanda koma `,`

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    original_data,
sepertinya ini bisa diganti jadi `subProductId`, tapi kayanya ini juga seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +    subProductId,
sepertinya `subProductId` ini seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-05 08:04 UTC, fikrihaykal41 commented on dags/source/sql/dwh/L2/visibility/lgd_sub_product.sql
> +  ON A.subProductId = B.subProductId
sepertinya `subProductId` ini seharusnya formatnya diubah jadi `snake_case` di `L1`-nya

2022-07-07 05:49 UTC, ameliaksalwa reviewed
punteun berdasarkan query L2 ter-update sepertinya sudah clear, namun belum bisa di-execute karena tabel L1_visibility_lgd_sub_product belum update untuk field `sub_product_id`

2022-07-08 03:42 UTC, ameliaksalwa approved these changes
sepertinya sudah aman, approved yey

2022-07-08 07:06 UTC, fikrihaykal41 approved these changes
sejauh yg ku lihat sudah aman, approved

2022-07-11 02:08 UTC, merged